# Generated by Django 3.2.7 on 2021-11-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_notesmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
