# Generated by Django 3.2.7 on 2021-11-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_notesmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
