# Generated by Django 3.2.7 on 2021-11-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_notesmodel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesmodel',
            name='file',
        ),
        migrations.AddField(
            model_name='notesmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
