# Generated by Django 3.2.7 on 2021-11-09 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_rename_description_notesmodel_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notesmodel',
            old_name='user',
            new_name='post_author',
        ),
        migrations.AddField(
            model_name='notesmodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notesmodel',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notesmodel',
            name='body',
            field=models.TextField(),
        ),
    ]
